// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDodV7tuaFT2E_KratGVTlmuMYgzeqWw',
    appId: '1:349125687513:web:4ab33091bdeb02910be6c8',
    messagingSenderId: '349125687513',
    projectId: 'csc315andrewtrafton',
    authDomain: 'csc315andrewtrafton.firebaseapp.com',
    storageBucket: 'csc315andrewtrafton.appspot.com',
    measurementId: 'G-9BZHP44QDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV9YY7p1j7S2zCdlsMmjWGMqPLDa1VZ04',
    appId: '1:349125687513:android:b30c8d59780b2ff20be6c8',
    messagingSenderId: '349125687513',
    projectId: 'csc315andrewtrafton',
    storageBucket: 'csc315andrewtrafton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMPLxibygPz8N-5JeNv0YRfqDNkKo5aUA',
    appId: '1:349125687513:ios:9d4013c57ca8c3df0be6c8',
    messagingSenderId: '349125687513',
    projectId: 'csc315andrewtrafton',
    storageBucket: 'csc315andrewtrafton.appspot.com',
    iosClientId: '349125687513-snhfoef6hj1fj232s2bdrfau7m9elvlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.uncwLandmarkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMPLxibygPz8N-5JeNv0YRfqDNkKo5aUA',
    appId: '1:349125687513:ios:9d4013c57ca8c3df0be6c8',
    messagingSenderId: '349125687513',
    projectId: 'csc315andrewtrafton',
    storageBucket: 'csc315andrewtrafton.appspot.com',
    iosClientId: '349125687513-snhfoef6hj1fj232s2bdrfau7m9elvlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.uncwLandmarkApp',
  );
}
